<!-- BUTTON -->
<div class="row">
	<div class="text-center">
		<a class="btn btn-app" href="#" onclick="javascript:submitFormAdmin();"><i class="fa fa-save"></i> Save</a> 
		<a class="btn btn-app" href="#"><i class="fa fa-arrow-circle-left"></i> Cancel</a>
	</div>
</div>
<?php 
	$myForm				= $this->myForm;
	$myForm->prepare();
?>

<?php echo $myForm->showMessage();?>
<div class="box box-info">
	<div class="box-body">
		<?php
			echo $this->form()->openTag($myForm);
				echo $this->partialLoop('form_row.phtml', array(
						array('elm' => $myForm->get('name')),
						array('elm' => $myForm->get('ordering')),
						array('elm' => $myForm->get('status')),
				));
			echo $this->formHidden($myForm->get('id'));
			echo $this->form()->closeTag();
		?>
	</div>
</div>